model_params: {
  enable_rangefinder: False,
  enable_teraranger: False,
  enable_rangefinder_up: False,
  enable_ground_truth: False,
  enable_mobius_camera_front: False,
  enable_mobius_camera_down: False,
  enable_mobius_camera_back_left: False,
  enable_mobius_camera_back_right: False,
  enable_realsense_front_pitched: False,
  enable_realsense_down: False,
  enable_realsense_top: False,
  enable_realsense_front: False,
  enable_realsense_up: False,
  use_realistic_realsense: False,
  enable_whycon_box: False,
  enable_bluefox_camera: False,
  enable_bluefox_camera_reverse: False,
  enable_fisheye_camera: False,
  enable_magnetic_gripper: False,
  enable_scanse_sweep: False,
  enable_pendulum: False,
  enable_rplidar: False,
  enable_teraranger_tower_evo: False,
  enable_timepix: False,
  enable_thermal_camera: False,
  enable_velodyne: False,
  enable_ouster: False,
  ouster_model: None,
  use_gpu_ray: False,
  enable_light: False,
  enable_servo_camera: False,
  enable_ball_holder: False,
  enable_water_gun: False,
  enable_parachute: False,
  wall_challenge: False,
  fire_challenge_blanket: False,
  gps_indoor_jamming: False,
  enable_uv_leds: False,
  uvled_fr_l: None,
  uvled_fr_r: None,
  enable_uv_leds_beacon: False,
  uvled_beacon_f: None,
  enable_uv_camera: False,
  uvcam_calib_file: None,
  uvcam_occlusions: False,
  debug: False
}
