#!/bin/sh
#
# @name DJI F450 SITL
#
# @type Quadcopter x
#
# @maintainer Petr Stibinger <stibipet@fel.cvut.cz>
#

sh /etc/init.d/rc.mc_defaults

set MAV_TYPE 2

set MIXER quad_x

param set BAT_N_CELLS 6
param set BAT_CAPACITY 8000
param set BAT_V_EMPTY 3.6
param set BAT_V_CHARGED 4.2
param set BAT_V_LOAD_DROP 0.4
