<?xml version="1.0"?>

<robot name="t650" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Args {-->
  <!-- Properties that can be assigned at build time as arguments.
  Is there a reason not to make all properties arguments?
  -->
  <xacro:property name="namespace" value="$(arg namespace)" />

  <xacro:arg name='name' default='t650' />
  <xacro:arg name='mavlink_addr' default='INADDR_ANY' />
  <xacro:arg name='mavlink_udp_port' default='14560' />
  <xacro:arg name='mavlink_tcp_port' default='4560' />
  <xacro:arg name='serial_enabled' default='false' />
  <xacro:arg name='serial_device' default='/dev/ttyACM0' />
  <xacro:arg name='baudrate' default='921600' />
  <xacro:arg name='qgc_addr' default='INADDR_ANY' />
  <xacro:arg name='qgc_udp_port' default='14550' />
  <xacro:arg name='sdk_addr' default='INADDR_ANY' />
  <xacro:arg name='sdk_udp_port' default='14540' />
  <xacro:arg name='hil_mode' default='false' />
  <xacro:arg name='hil_state_level' default='false' />
  <xacro:arg name='send_vision_estimation' default='false' />
  <xacro:arg name='send_odometry' default='false' />
  <xacro:arg name='use_lockstep' default='true' />
  <xacro:arg name='use_tcp' default='true' />
  <xacro:arg name='vehicle_is_tailsitter' default='false' />
  <xacro:arg name='visual_material' default='DarkGrey' />
  <xacro:arg name='gps_indoor_jamming' default='false' />
  <!--}-->

  <!-- includes definition of sensors xacros and Math {-->
    <!-- macros for gazebo plugins, sensors -->
    <xacro:include filename="$(arg mrs_robots_description_dir)/urdf/component_snippets.xacro" />
  <!--}-->

  <!-- ================================================================== -->
  <!-- ||                    parameters definition                     || -->
  <!-- ================================================================== -->

  <!-- Robot parameters and arguments {-->
  <xacro:property name="mass" value="3.5" /> <!-- [kg] -->
  <xacro:property name="body_radius" value="0.325" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.15" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.005" /> <!-- [kg] -->
  <xacro:property name="radius_rotor" value="0.195" /> <!-- [m] -->
  <xacro:property name="rotor_offset" value="0.021" /> <!-- [m] -->
  <xacro:property name="propeller_offset" value="0.01" /> <!-- [m] -->
  <xacro:property name="arm_length" value="0.3" /> <!-- [m] -->
  <xacro:property name="leg_height" value="0.24" /> 
  <!-- <xacro:property name="leg_height" value="0.15" /> -->
  <xacro:property name="leg_offset_r" value="0.05" /> <!-- [m] -->
  <xacro:property name="leg_radius" value="0.012" /> <!-- [m] -->

  <xacro:arg name="use_battery_mount" default="true" /> <!-- [m] -->
  <!--}-->

  <!-- Motor constants {-->
  <xacro:property name="rotor_velocity_slowdown_sim" value="0.0159236" />
  <xacro:property name="motor_constant" value="23.0" /> <!-- [kg.m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="${1.0 / 80.0}" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="${1.0 / 40.0}" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="0.1" /> <!--orig 8.06428e-04 -->
  <xacro:property name="rolling_moment_coefficient" value="1.0e-6" />
  <!--}-->

  <!-- Inertia constants {-->
  <xacro:property name="inertia_body_radius" value="0.25" /> <!-- [m] -->
  <xacro:property name="inertia_body_height" value="0.05" /> <!-- [m] -->
  <!--}-->

  <!-- Meshes {-->
  <!-- drone parts -->
  <xacro:property name="top_board_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_top_board.dae" />
  <xacro:property name="bottom_board_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_bottom_board.dae" />
  <xacro:property name="arm_mesh_file_front" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_arm_black.dae" />
  <xacro:property name="arm_mesh_file_back" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_arm_red.dae" />
  <xacro:property name="leg_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_leg.dae"/>
  <!-- <xacro:property name="leg_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_short_leg.dae"/> -->
  <xacro:property name="rotor_mesh_file_front" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_motor_black.dae" />
  <xacro:property name="rotor_mesh_file_back" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_motor_orange.dae" />
  <xacro:property name="prop_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_prop_low_poly.dae"/>
  <xacro:property name="pixhawk_mesh_file" value="package://mrs_robots_description/meshes/sensors/pixhawk.dae" />
  <xacro:property name="nuc_mesh_file" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_nuc.dae" />

  <!-- holders -->
  <xacro:property name="battery_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_battery_mount.dae" />
  <xacro:property name="bluefox_garmin_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_bluefox_garmin_mount.dae" />
  <xacro:property name="ouster_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_ouster_mount.dae" />
  <xacro:property name="rplidar_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_rplidar_mount.dae" />
  <xacro:property name="uvdar_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_uvdar_mount.dae" />
  <xacro:property name="realsense_front_mount_mesh" value="package://mrs_robots_description/meshes/tarot/t650/tarot_t650_realsense_front_mount.dae" />

  <!-- scales -->
  <xacro:property name="mesh_scale" value="1 1 1"/>
  <xacro:property name="mesh_scale_prop_ccw" value="1 1 1"/>
  <xacro:property name="mesh_scale_prop_cw" value="-1 1 1"/>
  <xacro:property name="mesh_scale_milimeters" value="0.001 0.001 0.001" />
  <!--}-->

  <!-- ================================================================== -->
  <!-- ||                    bare body definitions                     || -->
  <!-- ================================================================== -->

  <!-- Inertia blocks {-->
  <!-- cylinder body -->
  <xacro:property name="body_inertia">
    <inertia
      ixx="${mass * (3 * inertia_body_radius * inertia_body_radius + inertia_body_height * inertia_body_height) / 12}"
      iyy="${mass * (3 * inertia_body_radius * inertia_body_radius + inertia_body_height * inertia_body_height) / 12}"
      izz="${mass * inertia_body_radius * inertia_body_radius / 2}"
      ixy="0" ixz="0" iyz="0"/>
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <!-- <inertia -->
      <!--   ixx="${1/12 * mass_rotor * (0.015 * 0.015 + 0.003 * 0.003) * rotor_velocity_slowdown_sim}" -->
      <!--   iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.003 * 0.003) * rotor_velocity_slowdown_sim}" -->
      <!--   izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.015 * 0.015) * rotor_velocity_slowdown_sim}" -->
      <!--   ixy="0.0" ixz="0.0"  iyz="0.0" /> -->
    <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- Instantiate multirotor_base_macro {-->
  <xacro:multirotor_base_without_mesh_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_radius="${body_radius}"
    body_height="${body_height}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_without_mesh_macro>
  <!--}-->
  <!--}-->

  <!-- Body parts {-->

  <!-- Boards {-->
  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="bottom_board"
    mesh_file="${bottom_board_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
  <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 0" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="top_board"
    mesh_file="${top_board_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
  <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 0" />
  </xacro:textured_visual_macro>
  <!--}-->

  <!-- Arms {-->
  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="front_right_arm"
    mesh_file="${arm_mesh_file_front}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
  <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 -${rad45}" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="back_right_arm"
    mesh_file="${arm_mesh_file_back}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 -${rad135}" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="front_left_arm"
    mesh_file="${arm_mesh_file_front}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 ${rad45}" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="back_left_arm"
    mesh_file="${arm_mesh_file_back}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="0 0 ${-1.7*body_height}" rpy="0 0 ${rad135}" />
  </xacro:textured_visual_macro>
  <!--}-->

  <!-- intel nuc {-->
  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="NUC"
    mesh_file="${nuc_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="0.002 0 ${-1.7*body_height}" rpy="0 0 0" />
  </xacro:textured_visual_macro>
  <!--}-->

  <!-- pixhawk {-->
  <xacro:visual_macro
    robot_namespace="${namespace}"
    name="pixhawk"
    mesh_file="${pixhawk_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link"
    color="DarkGrey">
    <origin xyz="0 0 -0.0075" rpy="0 0 0" />
  </xacro:visual_macro>
  <!--}-->

  <!-- Legs {-->
  <xacro:leg_macro
    robot_namespace="${namespace}"
    name="front_right_leg"
    mesh_file="${leg_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link"
    color="DarkGrey">
  <origin xyz="${(arm_length - leg_offset_r) * sin45} -${(arm_length - leg_offset_r) * sin45} ${-0.9*body_height}" rpy="0 0 -${rad45}" />
    <collision>
      <geometry>
        <cylinder length="${leg_height}" radius="${leg_radius}" />
      </geometry>
    </collision>
  </xacro:leg_macro>
  
  <xacro:leg_macro
    robot_namespace="${namespace}"
    name="front_left_leg"
    mesh_file="${leg_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link"
    color="DarkGrey">
  <origin xyz="${(arm_length - leg_offset_r) * sin45} ${(arm_length - leg_offset_r) * sin45} ${-0.9*body_height}" rpy="0 0 ${rad45}" />
    <collision>
      <geometry>
        <cylinder length="${leg_height}" radius="${leg_radius}" />
      </geometry>
    </collision>
  </xacro:leg_macro>

  <xacro:leg_macro
    robot_namespace="${namespace}"
    name="rear_left_leg"
    mesh_file="${leg_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link"
    color="Orange">
  <origin xyz="-${(arm_length - leg_offset_r) * sin45} ${(arm_length - leg_offset_r) * sin45} ${-0.9*body_height}" rpy="0 0 ${rad135}" />
    <collision>
      <geometry>
        <cylinder length="${leg_height}" radius="${leg_radius}" />
      </geometry>
    </collision>
  </xacro:leg_macro>

  <xacro:leg_macro
    robot_namespace="${namespace}"
    name="rear_right_leg"
    mesh_file="${leg_mesh_file}"
    mesh_scale="${mesh_scale}"
    parent="base_link"
    color="Orange">
  <origin xyz="-${(arm_length - leg_offset_r) * sin45} -${(arm_length - leg_offset_r) * sin45} ${-0.9*body_height}" rpy="0 0 -${rad135}" />
    <collision>
      <geometry>
        <cylinder length="${leg_height}" radius="${leg_radius}" />
      </geometry>
    </collision>
  </xacro:leg_macro>
  <!--}-->

  <!-- Motors {-->
  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="front_right_rotor"
    mesh_file="${rotor_mesh_file_front}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
  <origin xyz="${arm_length * sin45} -${arm_length * sin45} -${rotor_offset}" rpy="0 0 0" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="back_right_rotor"
    mesh_file="${rotor_mesh_file_back}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="-${arm_length * sin45} -${arm_length * sin45} -${rotor_offset}" rpy="0 0 0" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="front_left_rotor"
    mesh_file="${rotor_mesh_file_front}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="${arm_length * sin45} ${arm_length * sin45} -${rotor_offset}" rpy="0 0 0" />
  </xacro:textured_visual_macro>

  <xacro:textured_visual_macro
    robot_namespace="${namespace}"
    name="back_left_rotor"
    mesh_file="${rotor_mesh_file_back}"
    mesh_scale="${mesh_scale}"
    parent="base_link">
    <origin xyz="-${arm_length * sin45} ${arm_length * sin45} -${rotor_offset}" rpy="0 0 0" />
  </xacro:textured_visual_macro>
  <!--}-->

  <!-- Propellers + thrust physics {-->
  <xacro:textured_vertical_rotor robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh_file="${prop_mesh_file}"
    mesh_scale="${mesh_scale_prop_cw}">
    <origin xyz="${arm_length * sin45} -${arm_length * sin45} ${propeller_offset}"  rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:textured_vertical_rotor>

  <xacro:textured_vertical_rotor robot_namespace="${namespace}"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh_file="${prop_mesh_file}"
    mesh_scale="${mesh_scale_prop_cw}">
    <origin xyz="-${arm_length * sin45} ${arm_length * sin45} ${propeller_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:textured_vertical_rotor>
  
  <xacro:textured_vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh_file="${prop_mesh_file}"
    mesh_scale="${mesh_scale_prop_cw}">
    <origin xyz="${arm_length * sin45} ${arm_length * sin45} ${propeller_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:textured_vertical_rotor>

  <xacro:textured_vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh_file="${prop_mesh_file}"
    mesh_scale="${mesh_scale_prop_ccw}">
    <origin xyz="-${arm_length * sin45} -${arm_length * sin45} ${propeller_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:textured_vertical_rotor>
  <!--}-->

  <!-- Battery mount and battery{-->
  <xacro:if value="$(arg use_battery_mount)">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="battery_mount"
      mesh_file="${battery_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
      <origin xyz="0.0 0 -${0.24*body_height}" rpy="0 0 0" />
    </xacro:visual_macro>

    <xacro:visual_macro_common_geometry_type
      robot_namespace="${namespace}"
      name="battery"
      parent="base_link"
      color="Grey">
      <origin xyz="0.0 0 -${0.45*body_height}" rpy="0 0 0" />
      <geometry>
        <box size="0.16 0.065 0.044" />
      </geometry>
    </xacro:visual_macro_common_geometry_type>
  </xacro:if>
  <!--}-->

  <!--}-->

  <!-- ================================================================== -->
  <!-- ||                 mandatory sensor definitions                 || -->
  <!-- ================================================================== -->

  <!-- Mavlink interface {-->
  <!-- Instantiate mavlink telemetry interface. -->
  <xacro:mavlink_interface_macro
    namespace="${namespace}"
    imu_sub_topic="/imu"
    gps_sub_topic="/gps"
    mag_sub_topic="/mag"
    baro_sub_topic="/baro"
    mavlink_addr="$(arg mavlink_addr)"
    mavlink_udp_port="$(arg mavlink_udp_port)"
    mavlink_tcp_port="$(arg mavlink_tcp_port)"
    serial_enabled="$(arg serial_enabled)"
    serial_device="$(arg serial_device)"
    baudrate="$(arg baudrate)"
    qgc_addr="$(arg qgc_addr)"
    qgc_udp_port="$(arg qgc_udp_port)"
    sdk_addr="$(arg sdk_addr)"
    sdk_udp_port="$(arg sdk_udp_port)"
    hil_mode="$(arg hil_mode)"
    hil_state_level="$(arg hil_state_level)"
    vehicle_is_tailsitter="$(arg vehicle_is_tailsitter)"
    send_vision_estimation="$(arg send_vision_estimation)"
    send_odometry="$(arg send_odometry)"
    enable_lockstep="$(arg use_lockstep)"
    use_tcp="$(arg use_tcp)"
    >
  </xacro:mavlink_interface_macro>
  <!--}-->

  <!-- GPS {-->
  <xacro:gps_plugin_macro
    namespace="${namespace}"
    gps_noise="true"
    gps_indoor_jamming="$(arg gps_indoor_jamming)">
    >
  </xacro:gps_plugin_macro>

  <xacro:if value="$(arg gps_indoor_jamming)">
    <xacro:gps_satelites_blocking_macro
      namespace="${namespace}"
      parent_link="base_link">
    </xacro:gps_satelites_blocking_macro>
  </xacro:if>
  <!--}-->

  <!-- Magnetometer {-->
  <xacro:magnetometer_plugin_macro
    namespace="${namespace}"
    pub_rate="20"
    noise_density="0.0004"
    random_walk="0.0000064"
    bias_correlation_time="600"
    mag_topic="/mag"
    >
  </xacro:magnetometer_plugin_macro>
  <!--}-->

  <!-- Barometer {-->
  <xacro:barometer_plugin_macro
    namespace="${namespace}"
    pub_rate="10"
    baro_topic="/baro"
    >
  </xacro:barometer_plugin_macro>
  <!--}-->

  <!-- IMU (ADIS16448) {-->
  <xacro:imu_plugin_macro
    namespace="${namespace}"
    imu_suffix=""
    parent_link="base_link"
    imu_topic="/imu"
    mass_imu_sensor="0.015"
    gyroscope_noise_density="0.0003394"
    gyroscopoe_random_walk="0.000038785"
    gyroscope_bias_correlation_time="1000.0"
    gyroscope_turn_on_bias_sigma="0.0087"
    accelerometer_noise_density="0.004"
    accelerometer_random_walk="0.006"
    accelerometer_bias_correlation_time="300.0"
    accelerometer_turn_on_bias_sigma="0.1960"
    >
    <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:imu_plugin_macro>
  <!--}-->

  <!-- ================================================================== -->
  <!-- ||                  optional sensor definitions                 || -->
  <!-- ================================================================== -->

  <!-- Ground truth {-->
  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:odometry_plugin_macro
      namespace="${namespace}"
      odometry_sensor_suffix="_ground_truth"
      parent_link="base_link"
      topic_name="ground_truth"
      frame_name="world"
      mass_odometry_sensor="0.00001"
      noise="0"
      frame_rate="150"
      xyz_offset="0 0 0"
      rpy_offset="0 0 0">
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </xacro:odometry_plugin_macro>
  </xacro:if>
  <!--}-->

  <!-- ======================= rangefinder sensors ======================-->

  <!-- Garmin {-->
  <xacro:if value="$(arg enable_rangefinder)">
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation=""
      x="0.0"
      y="-0.221"
      z="-0.025"
      roll="0"
      pitch="${rad90}"
      yaw="${rad90}"
      >
    </xacro:garmin_macro>
  </xacro:if>
  <!--}-->

  <!-- Garmin looking up {-->
  <xacro:if value="$(arg enable_rangefinder_up)">
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation="_up"
      x="0.0"
      y="0.08"
      z="-0.0075"
      roll="0"
      pitch="-${rad90}"
      yaw="-${rad90}"
      >
    </xacro:garmin_macro>
  </xacro:if>
  <!--}-->

  <!-- ========================== LIDAR sensors ========================= -->

  <!-- Scanse Sweep {-->
  <xacro:if value="$(arg enable_scanse_sweep)">
    <xacro:scanse_sweep_macro
      namespace="${namespace}"
      x="0.0"
      y="0.0"
      z="0.12"
      roll="0"
      pitch="0"
      yaw="0"
      >
    </xacro:scanse_sweep_macro>
  </xacro:if>
  <!--}-->

  <!-- Rplidar {-->
  <xacro:if value="$(arg enable_rplidar)">
    <xacro:rplidar_macro
      namespace="${namespace}"
      x="0.0"
      y="0.0"
      z="0.107"
      roll="0"
      pitch="0"
      yaw="0"
      >
    </xacro:rplidar_macro>
  </xacro:if>
  <!--}-->

  <!-- Velodyne  {-->
  <xacro:if value="$(arg enable_velodyne)">

    <!-- VLP-16 (default) -->
    <xacro:property name="sensor_name" value="velodyne" />
    <xacro:property name="lasers" value="16" />
    <xacro:property name="vfov_angle" value="30" />
    <xacro:property name="range" value="100" />

    <xacro:velodyne_macro
      namespace="${namespace}"
      sensor_name="${sensor_name}"
      x="0"
      y="0"
      z="0.073"
      roll="0"
      pitch="0"
      yaw="0"
      rot_freq="20"
      lasers="${lasers}"
      vfov_angle="${vfov_angle}"
      max_range="${range}"
      noise="0.01"
      enable_gpu_ray="$(arg use_gpu_ray)"
      >
    </xacro:velodyne_macro>
  </xacro:if>
  <!--}-->

  <!-- Ouster {-->
  <xacro:if value="$(arg enable_ouster)">
  <xacro:property name="ouster_model" value="$(arg ouster_model)" />

    <!-- OS1-16 Generation 1 (default) -->
    <xacro:property name="sensor_name" value="os1" />
    <xacro:property name="lasers" value="16" />
    <xacro:property name="vfov_angle" value="33.2" />
    <xacro:property name="range" value="120" />
    <xacro:if value="${ouster_model == 'OS1-16'}">
      <xacro:property name="sensor_name" value="os1" />
      <xacro:property name="lasers" value="16" />
      <xacro:property name="vfov_angle" value="33.2" />
      <xacro:property name="range" value="120" />
    </xacro:if>

    <!-- OS0 {-->
    <!-- OS0-32 -->
    <xacro:if value="${ouster_model == 'OS0-32'}">
      <xacro:property name="sensor_name" value="os0" />
      <xacro:property name="lasers" value="32" />
      <xacro:property name="vfov_angle" value="90" />
      <xacro:property name="range" value="55" />
    </xacro:if>

    <!-- OS0-64 -->
    <xacro:if value="${ouster_model == 'OS0-64'}">
      <xacro:property name="sensor_name" value="os0" />
      <xacro:property name="lasers" value="64" />
      <xacro:property name="vfov_angle" value="90" />
      <xacro:property name="range" value="55" />
    </xacro:if>

    <!-- OS0-128 -->
    <xacro:if value="${ouster_model == 'OS0-128'}">
      <xacro:property name="sensor_name" value="os0" />
      <xacro:property name="lasers" value="128" />
      <xacro:property name="vfov_angle" value="90" />
      <xacro:property name="range" value="55" />
    </xacro:if>

    <!--}-->

    <!-- OS1 Generation 2 {-->
    <!-- OS1-32 Generation 2 -->
    <xacro:if value="${ouster_model == 'OS1-32'}">
      <xacro:property name="sensor_name" value="os1" />
      <xacro:property name="lasers" value="32" />
      <xacro:property name="vfov_angle" value="45" />
      <xacro:property name="range" value="120" />
    </xacro:if>

    <!-- OS1-64 Generation 2 -->
    <xacro:if value="${ouster_model == 'OS1-64'}">
      <xacro:property name="sensor_name" value="os1" />
      <xacro:property name="lasers" value="64" />
      <xacro:property name="vfov_angle" value="45" />
      <xacro:property name="range" value="120" />
    </xacro:if>

    <!-- OS1-128 Generation 2 -->
    <xacro:if value="${ouster_model == 'OS1-128'}">
      <xacro:property name="sensor_name" value="os1" />
      <xacro:property name="lasers" value="128" />
      <xacro:property name="vfov_angle" value="45" />
      <xacro:property name="range" value="120" />
    </xacro:if>

    <!--}-->

    <!-- OS2 {-->
    <!-- OS2-32 -->
    <xacro:if value="${ouster_model == 'OS2-32'}">
      <xacro:property name="sensor_name" value="os2" />
      <xacro:property name="lasers" value="32" />
      <xacro:property name="vfov_angle" value="22.5" />
      <xacro:property name="range" value="240" />
    </xacro:if>

    <!-- OS2-64 -->
    <xacro:if value="${ouster_model == 'OS2-64'}">
      <xacro:property name="sensor_name" value="os2" />
      <xacro:property name="lasers" value="64" />
      <xacro:property name="vfov_angle" value="22.5" />
      <xacro:property name="range" value="240" />
    </xacro:if>

    <!-- OS2-128 -->
    <xacro:if value="${ouster_model == 'OS2-128'}">
      <xacro:property name="sensor_name" value="os2" />
      <xacro:property name="lasers" value="128" />
      <xacro:property name="vfov_angle" value="22.5" />
      <xacro:property name="range" value="240" />
    </xacro:if>

    <!--}-->

  <xacro:ouster_macro
    namespace="${namespace}"
    sensor_name="${sensor_name}"
    x="0"
    y="0"
    z="0.073"
    roll="0"
    pitch="0"
    yaw="0"
    rot_freq="10"
    lasers="${lasers}"
    vfov_angle="${vfov_angle}"
    max_range="${range}"
    noise="0.03"
    enable_gpu_ray="$(arg use_gpu_ray)"
    >
  </xacro:ouster_macro>
  </xacro:if>
  <!--}-->

  <!-- ========================= camera sensors ========================= -->

  <!-- Bluefox placements{-->

  <!-- reverse {-->
  <xacro:if value="$(arg enable_bluefox_camera_reverse)">
    <xacro:bluefox_camera_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="bluefox_optflow"
      frame_rate="100.0"
      hfov="2.1"
      noise="0.007"
      parent_frame_name="${namespace}/fcu"
      camera_frame_name="${namespace}/bluefox_optflow_optical"
      sensor_base_frame_name="${namespace}/bluefox_optflow"
      x="0.0"
      y="-0.15"
      z="-0.057"
      roll="0"
      pitch="${rad90}"
      yaw="${rad180}"
      >
    </xacro:bluefox_camera_macro>
  </xacro:if>
  <!--}-->

  <!-- classic {-->
  <xacro:if value="$(arg enable_bluefox_camera)">
    <xacro:bluefox_camera_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="bluefox_optflow"
      frame_rate="100.0"
      hfov="2.1"
      noise="0.007"
      parent_frame_name="${namespace}/fcu"
      camera_frame_name="${namespace}/bluefox_optflow_optical"
      sensor_base_frame_name="${namespace}/bluefox_optflow"
      x="0.0"
      y="-0.15"
      z="-0.057"
      roll="0"
      pitch="${rad90}"
      yaw="0"
      >
    </xacro:bluefox_camera_macro>
  </xacro:if>
  <!--}-->

  <!--} Bluefox placements-->

  <!-- Realsense placements {-->
  
  <!-- front {-->
  <xacro:if value="$(arg enable_realsense_front)">
    <!-- sensor -->
    <xacro:realsense_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="realsense_front"
      parent_frame_name="${namespace}/fcu"
      enable_realistic_realsense="$(arg use_realistic_realsense)"
      x="0.17"
      y="-0.011"
      z="-0.063"
      roll="0"
      pitch="0"
      yaw="0">
    </xacro:realsense_macro>
  </xacro:if>
  <!--}-->
  
  <!--} realsense placements-->

  <!-- Mobius placements {-->

  <!-- front {-->
  <xacro:if value="$(arg enable_mobius_camera_front)">
    <xacro:mobius_camera_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="mobius_front"
      frame_rate="30.0"
      parent_frame_name="${namespace}/fcu"
      camera_frame_name="${namespace}/mobius_front_optical"
      sensor_base_frame_name="${namespace}/mobius_front"
      x="0.2"
      y="0.0"
      z="-0.04"
      roll="0"
      pitch="0"
      yaw="0"
      >
    </xacro:mobius_camera_macro>
  </xacro:if>
  <!--}-->
  
  <!--} mobius placements -->

  <!-- Thermal camera {-->
  <xacro:if value="$(arg enable_thermal_camera)">
    <!-- top -->
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/top_optical"
      camera_topic_name="/${namespace}/thermal/top"
      parent_link="base_link"
      camera_suffix="thermal/top"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0"
      z="-0.085"
      roll="0"
      pitch="-${rad30}"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/top"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <!-- middle -->
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/middle_optical"
      camera_topic_name="/${namespace}/thermal/middle"
      parent_link="base_link"
      camera_suffix="thermal/middle"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0"
      z="-0.085"
      roll="0"
      pitch="0"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/middle"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <!-- bottom -->
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/bottom_optical"
      camera_topic_name="/${namespace}/thermal/bottom"
      parent_link="base_link"
      camera_suffix="thermal/bottom"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0"
      z="-0.085"
      roll="0"
      pitch="${rad30}"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/bottom"
      color="Yellow">
    </xacro:thermal_camera_macro>
  </xacro:if>
  <!--}-->

  <!-- UV camera {-->
  <xacro:if value="$(arg enable_uv_camera)">

    <xacro:uvcam_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="1"          
      frame_rate="80"     
      camera_publish_topic="/${namespace}/uvdar_bluefox_left/image_raw"
      calibration_file="$(arg uvcam_calib_file)">
    <origin xyz="0.037 0.1175 0.057" rpy="0 0 ${rad70}" />
    </xacro:uvcam_macro>  

    <xacro:uvcam_macro    
      namespace="${namespace}"
      parent_link="base_link"
      number="2"          
      frame_rate="80"     
      camera_publish_topic="/${namespace}/uvdar_bluefox_right/image_raw"
      calibration_file="$(arg uvcam_calib_file)">
    <origin xyz="0.037 -0.1175 0.057" rpy="0 0 -${rad70}" />
    </xacro:uvcam_macro>  

  </xacro:if>
  <!--}-->

  <!-- Servo camera {-->
  <xacro:if value="$(arg enable_servo_camera)">
    <xacro:servo_camera_macro
      namespace="${namespace}"
      name="servo_camera_macro"
      parent="base_link"
      offset_x="0.2"
      offset_y="0.0"
      offset_z="-0.10"
      offset_roll="0.0"
      offset_yaw="0.0"
      offset_pitch="0.0"
      max_pitch_rate="0.1"
      camera_type="servo_camera"
      update_rate="30.0">
    </xacro:servo_camera_macro>
  </xacro:if>
  <!--}-->

  <!-- ========================== other sensors ========================= -->

  <!-- Teraranger Tower Evo {-->
  <xacro:if value="$(arg enable_teraranger_tower_evo)">
    <xacro:teraranger_tower_evo_macro
      namespace="${namespace}"
      parent_link="base_link"
      frame_name="${namespace}/teraranger_tower"
      parent_frame_name="${namespace}/fcu"
      >
      <origin xyz="0.0 0.0 0.178" rpy="0 0 0" />
    </xacro:teraranger_tower_evo_macro>
  </xacro:if>
  <!--}-->

  <!-- Magnetic gripper {-->
  <xacro:if value="$(arg enable_magnetic_gripper)">
    <xacro:magnet_gripper_macro
      namespace="${namespace}"
      name="gripper"
      color="White"
      parent="base_link">
      <origin xyz="0 0 -${0.20/2 + 0.01}" rpy="0 0 ${rad90}" />
    </xacro:magnet_gripper_macro>
  </xacro:if>
  <!--}-->

  <!-- Timepix {-->
  <xacro:if value="$(arg enable_timepix)">
    <xacro:timepix_macro
      namespace="${namespace}"
      name="timepix"
      parent="base_link"
      color="Green">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:timepix_macro>
  </xacro:if>
  <!--}-->

<!-- Water gun {-->
<xacro:if value="$(arg enable_water_gun)">
  <xacro:water_gun_macro
    namespace="${namespace}"
    name="water_gun_macro"
    parent="base_link"
    color="Red"
    muzzle_velocity="10.0"
    particle_capacity="30"
    spread="1.0"
    spawning_reservoir="the_void"
    offset_x="0.2"
    offset_y="0.0"
    offset_z="-0.1"
    size_x="0.2"
    size_y="0.05"
    size_z="0.05">
  <origin xyz="0 0 0" rpy="0 0 0" />
</xacro:water_gun_macro>
  </xacro:if>
  <!--}-->

  <!-- UV leds {-->

  <!-- UV led - hexarotor configuration {-->
  <xacro:macro name="uvled_hexarotor"
    params="f1 f2 namespace parent_link">
    <!-- UV LED -->
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="1"
      frequency="${f1}">
      <origin xyz="0.2382 0.1375 -0.07" rpy="0 1.57079632679 0.5236" />
    </xacro:uvled_macro>
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="2"
      frequency="${f1}">
      <origin xyz="0 0.2750 -0.07" rpy="0 1.57079632679 1.5708" />
    </xacro:uvled_macro>
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="3"
      frequency="${f1}">
      <origin xyz="-0.2382 0.1375 -0.07" rpy="0 1.57079632679 2.6180" />
    </xacro:uvled_macro>
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="4"
      frequency="${f2}">
      <origin xyz="-0.2382 -0.1375 -0.07" rpy="0 1.57079632679 3.6652" />
    </xacro:uvled_macro>
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="5"
      frequency="${f2}">
      <origin xyz="0 -0.2750 -0.07" rpy="0 1.57079632679 4.7124" />
    </xacro:uvled_macro>
    <xacro:uvled_macro
      namespace="${namespace}"
      parent_link="base_link"
      number="6"
      frequency="${f2}">
      <origin xyz="0.2382 -0.1375 -0.07" rpy="0 1.57079632679 5.7596" />
    </xacro:uvled_macro>
  </xacro:macro>
  <!--}-->

  <xacro:if value="$(arg enable_uv_leds)">
    <xacro:uvled_hexarotor
      f1="$(arg uvled_fr_l)"
      f2="$(arg uvled_fr_r)"
      namespace="${namespace}"
      parent_link="base_link"/>
  </xacro:if>
  <!--}-->

  <!-- Light {-->
  <xacro:if value="$(arg enable_light)">
    <xacro:light_macro
      namespace="${namespace}"
      name="light_macro"
      parent="base_link"
      offset_x="0.2"
      offset_y="0.0"
      offset_z="-0.10"
      offset_roll="0.0"
      offset_yaw="0.0"
      offset_pitch="0.0"
      max_pitch_rate="0.1"
      initial_on="1"
      update_rate="30.0">
    </xacro:light_macro>
  </xacro:if>
  <!--}-->

  <!-- ================================================================== -->
  <!-- ||         other equipment definitions (holders, boxes ...)     || -->
  <!-- ================================================================== -->

  <!-- ============================= holders ============================ -->

  <!-- Ouster and Velodyne mount {-->
  <xacro:if value="${('$(arg enable_ouster)' == 'true') or ('$(arg enable_velodyne)' == 'true')}">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="ouster_mount"
      mesh_file="${ouster_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
    <origin xyz="0 0 0.068" rpy="0 0 ${rad90}" />
    </xacro:visual_macro>
  </xacro:if>
  <!--}-->

  <!-- Rplidar and scanse mount {-->
  <xacro:if value="${('$(arg enable_rplidar)' == 'true') or ('$(arg enable_scanse_sweep)' == 'true')}">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="rplidar_mount"
      mesh_file="${rplidar_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
    <origin xyz="0 0 0.075" rpy="0 0 0" />
    </xacro:visual_macro>
  </xacro:if>
  <!--}-->

  <!-- Realsense front mount {-->
  <xacro:if value="$(arg enable_realsense_front)">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="realsense_front_mount"
      mesh_file="${realsense_front_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
      <origin xyz="0.125 0 -0.046" rpy="0 0 0" />
    </xacro:visual_macro>
  </xacro:if>
  <!--}-->

  <!-- Bluefox and garmin mount {-->
  <xacro:if value="${('$(arg enable_bluefox_camera)' == 'true') or ('$(arg enable_bluefox_camera_reverse)' == 'true') or ('$(arg enable_rangefinder)' == 'true') or ('$(arg wall_challenge)' == 'true')}">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="bluefox_garmin_mount"
      mesh_file="${bluefox_garmin_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
      <origin xyz="0 -0.145 -0.025" rpy="0 0 -${rad90}" />
    </xacro:visual_macro>
  </xacro:if>
  <!--}-->

  <!-- UVDAR mount {-->
  <xacro:if value="$(arg enable_uv_camera)">
    <xacro:visual_macro
      robot_namespace="${namespace}"
      name="uvdar_mount"
      mesh_file="${uvdar_mount_mesh}"
      mesh_scale="${mesh_scale_milimeters}"
      parent="base_link"
      color="DarkGrey">
    <origin xyz="0.025 0 0.043" rpy="0 0 0" />
    </xacro:visual_macro>
  </xacro:if>
  <!--}-->

  <!-- ========================== other sensors ========================= -->

<!-- Parachute {-->
<xacro:if value="$(arg enable_parachute)">
  <xacro:parachute_macro
    namespace="${namespace}"
    name="parachute"
    parent="base_link"
    color="DarkGrey"
    offset_x="0.0"
    offset_y="0.0"
    offset_z="0.095">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:parachute_macro>
</xacro:if>
<!--}-->

  <!-- Pendulum {-->
  <xacro:if value="$(arg enable_pendulum)">
    <xacro:pendulum
      parent="base_link">
    </xacro:pendulum>
  </xacro:if>
  <!--}-->

  <!-- Ball holder {-->
  <xacro:if value="$(arg enable_ball_holder)">
    <xacro:ball_holder
      parent="base_link">
    </xacro:ball_holder>
  </xacro:if>
  <!--}-->

  <!-- MBZIRC profiles {-->

  <!-- Wall challenge {-->
  <xacro:if value="$(arg wall_challenge)">

    <!-- Garmin {-->
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation=""
      x="0.0"
      y="-0.221"
      z="-0.025"
      roll="0"
      pitch="${rad90}"
      yaw="${rad90}"
      >
    </xacro:garmin_macro>
    <!--}-->

    <!-- wide angle bluefox {-->
    <xacro:bluefox_camera_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="bluefox_brick"
      frame_rate="100.0"
      hfov="2.05"
      noise="0.007"
      parent_frame_name="${namespace}/fcu"
      camera_frame_name="${namespace}/bluefox_brick_optical"
      sensor_base_frame_name="${namespace}/bluefox_brick"
      x="0.0"
      y="-0.189"
      z="-0.068"
      roll="0"
      pitch="1.57079632679"
      yaw="-1.57079632679"
      >
    </xacro:bluefox_camera_macro>
    <!--}-->

    <!-- optflow bluefox {-->
    <xacro:bluefox_camera_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="bluefox_optflow"
      frame_rate="100.0"
      hfov="1.9"
      noise="0.007"
      parent_frame_name="${namespace}/fcu"
      camera_frame_name="${namespace}/bluefox_optflow_optical"
      sensor_base_frame_name="${namespace}/bluefox_optflow"
      x="-0.041"
      y="-0.185"
      z="-0.068"
      roll="0"
      pitch="1.57079632679"
      yaw="0"
      >
    </xacro:bluefox_camera_macro>
    <!--}-->

    <!-- tilted realsense {-->
    <xacro:realsense_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="realsense_down"
      parent_frame_name="${namespace}/fcu"
      enable_realistic_realsense="$(arg use_realistic_realsense)"
      x="0.15"
      y="0.15"
      z="-0.05"
      roll="-0.9727464"
      pitch="1.2572625"
      yaw="-2.5665787"
      >
    </xacro:realsense_macro>
    <!--}-->

  </xacro:if>
  <!--}-->

  <!-- Fire challenge {-->
  <xacro:if value="$(arg fire_challenge)">

    <!-- Garmin {-->
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation=""
      x="0.177"
      y="0.0735"
      z="-0.07"
      roll="0"
      pitch="1.57079632679"
      yaw="0"
      >
    </xacro:garmin_macro>
    <!--}-->

    <!-- Garmin up {-->
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation="_up"
      x="0.0"
      y="-0.08"
      z="0.01"
      roll="0"
      pitch="-1.57079632679"
      yaw="0"
      >
    </xacro:garmin_macro>
    <!--}--> 

    <!-- Rplidar {-->
    <xacro:rplidar_macro
      namespace="${namespace}"
      x="0.0"
      y="0.0"
      z="0.205"
      roll="0"
      pitch="0"
      yaw="0"
      >
    </xacro:rplidar_macro>
    <!--}-->

    <!-- Realsense front {-->
    <xacro:realsense_macro
      namespace="${namespace}"
      parent_link="base_link"
      camera_suffix="realsense_front"
      parent_frame_name="${namespace}/fcu"
      enable_realistic_realsense="$(arg use_realistic_realsense)"
      x="0.184"
      y="0"
      z="-0.04"
      roll="0"
      pitch="0"
      yaw="0">
    </xacro:realsense_macro>
    <!--}-->

    <!-- Thermal camera {-->
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/top_optical"
      camera_topic_name="/${namespace}/thermal/top"
      parent_link="base_link"
      camera_suffix="thermal/top"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0.055"
      z="-0.085"
      roll="0"
      pitch="-0.523598776"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/top"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/middle_optical"
      camera_topic_name="/${namespace}/thermal/middle"
      parent_link="base_link"
      camera_suffix="thermal/middle"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0.055"
      z="-0.085"
      roll="0"
      pitch="0"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/middle"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/bottom_optical"
      camera_topic_name="/${namespace}/thermal/bottom"
      parent_link="base_link"
      camera_suffix="thermal/bottom"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0.055"
      z="-0.085"
      roll="0"
      pitch="0.523598776"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/bottom"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <!--}-->

    <!-- Water gun {-->
    <xacro:water_gun_macro
      namespace="${namespace}"
      name="water_gun_macro"
      parent="base_link"
      color="Red"
      muzzle_velocity="10.0"
      particle_capacity="30"
      spread="1.0"
      spawning_reservoir="the_void"
      offset_x="0.2"
      offset_y="0.0"
      offset_z="-0.1"
      size_x="0.2"
      size_y="0.05"
      size_z="0.05">
      <origin xyz="0 0 0" rpy="0 -0.1 0" />
    </xacro:water_gun_macro>
    <!--}-->

  </xacro:if>
  <!--}-->

  <!-- Fire challenge (blanket dropping) {-->
  <xacro:if value="$(arg fire_challenge_blanket)">

    <!-- Garmin {-->
    <xacro:garmin_macro
      namespace="${namespace}"
      parent_link="base_link"
      orientation=""
      x="0.177"
      y="0.0735"
      z="-0.07"
      roll="0"
      pitch="1.57079632679"
      yaw="0"
      >
    </xacro:garmin_macro>
    <!--}-->

    <!-- Rplidar {-->
    <xacro:rplidar_macro
      namespace="${namespace}"
      x="0.0"
      y="0.0"
      z="0.205"
      roll="0"
      pitch="0"
      yaw="0"
      >
    </xacro:rplidar_macro>
    <!--}-->

    <!-- Thermal camera {-->
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/front_optical"
      camera_topic_name="/${namespace}/thermal/front"
      parent_link="base_link"
      camera_suffix="thermal/front"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0"
      z="-0.085"
      roll="0"
      pitch="1.0472"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/front"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <xacro:thermal_camera_macro
      namespace="${namespace}"
      camera_frame_name="thermal/bottom_optical"
      camera_topic_name="/${namespace}/thermal/bottom"
      parent_link="base_link"
      camera_suffix="thermal/bottom"
      frame_rate="14.0"
      hfov="0.575959"
      image_width="32"
      image_height="32"
      x="0.13"
      y="0"
      z="-0.085"
      roll="0"
      pitch="1.5708"
      yaw="0"
      parent_frame_name="${namespace}/fcu"
      sensor_base_frame_name="${namespace}/thermal/bottom"
      color="Yellow">
    </xacro:thermal_camera_macro>
    <!--}-->

  </xacro:if>
  <!--}-->

  <!--}-->

</robot>
